=== jaredrcleghorn/mod-assessment/ramls/schemas/main-class.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Main Class",
  "description": "A main class in the Library of Congress Classification, with counts",
  "type": "object",
  "properties": {
    "letter": {
      "description": "The letter that designates the main class",
      "type": "string"
    },
    "caption": {
      "description": "The caption that describes the main class",
      "type": "string"
    },
    "subclasses": {
      "description": "The subclasses of the main class",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "subclass.schema.json"
      }
    },
    "counts": {
      "description": "The counts, broken down by library",
      "type": "object"
    }
  },
  "additionalProperties": false,
  "required": [ "letter", "caption", "subclasses", "counts" ]
}

=== jaredrcleghorn/mod-assessment/ramls/examples/circulation-by-lcc-number.json
[
  {
    "letter": "P",
    "caption": "Language and Literature",
    "subclasses": [
      {
        "letters": "P",
        "caption": "Philology. Linguistics",
        "counts": {}
      },
      {
        "letters": "PR",
        "caption": "English literature",
        "counts": {
          "5d78803e-ca04-4b4a-aeae-2c63b924518b": {
            "checkouts": 1,
            "renewals": 0
          }
        }
      }
    ],
    "counts": {
      "5d78803e-ca04-4b4a-aeae-2c63b924518b": {
        "checkouts": 1,
        "renewals": 0
      }
    }
  }
]
